# # -*- coding: utf-8 -*-
# """GAN_image_generation_MNIST.ipynb
#
# Automatically generated by Colab.
#
# Original file is located at
#     https://colab.research.google.com/drive/16OWesReBHqCHK8e1YxTQPnU-ync9AoAX
# """
#
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# Generator Block
class Generator(nn.Module):
  def __init__(self, z_dim):
    super().__init__()
    self.model = nn.Sequential(
        nn.ConvTranspose2d(z_dim, 256, 7, 1, 0), # Input 1x1, Output 7x7
        nn.BatchNorm2d(256),
        nn.ReLU(),
        nn.ConvTranspose2d(256, 128, 4, 2, 1), # Input 7x7, Output 14x14
        nn.BatchNorm2d(128),
        nn.ReLU(),
        nn.ConvTranspose2d(128, 1, 4, 2, 1), # Input 14x14, Output 28x28
        nn.Tanh(),
    )
  def forward(self, x):
      return self.model(x)

# Discriminator Block
class Discriminator(nn.Module):
  def __init__(self):
    super().__init__()
    self.model = nn.Sequential(
        nn.Conv2d(1, 64, 4, 2, 1),
        nn.LeakyReLU(0.2),
        nn.Conv2d(64, 128, 4, 2, 1),
        nn.BatchNorm2d(128),
        nn.LeakyReLU(0.2),
        nn.Flatten(),
        nn.Linear(128*7*7, 1),
        nn.Sigmoid(),
    )

  def forward(self, x):
      return self.model(x)

device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Hyperparameters
batch_size = 128
lr = 0.002
z_dim = 100
epochs = 10



# Dataset loading
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Initializing loss function, generator, discriminator and optimizers
criterion = nn.BCELoss()
generator = Generator(z_dim).to(device)
discriminator = Discriminator().to(device)
optimizer_g = optim.Adam(generator.parameters(), lr=lr, betas=(0.5, 0.999))
optimizer_d = optim.Adam(discriminator.parameters(), lr=lr, betas=(0.5, 0.999))

def show_images(fake):
  img = fake.detach().cpu()[:16]
  grid = img.view(16, 28, 28)

  fig, axes = plt.subplots(4, 4, figsize=(5, 5))
  for i, ax in enumerate(axes.flatten()):
    ax.imshow(grid[i], cmap='gray')
    ax.axis('off')
  plt.show()

# Training Step
for epoch in range(epochs):
  for real, _ in dataloader:
    real = real.to(device)
    batch_size = real.size(0)

    # Training discriminator
    noise = torch.randn(batch_size, z_dim, 1, 1).to(device)
    fake = generator(noise)

    real_labels = torch.ones(batch_size, 1).to(device)
    # Label Smoothing
    real_labels = torch.ones(batch_size, 1).to(device) * 0.9

    fake_labels = torch.zeros(batch_size, 1).to(device)

    # Real Loss
    D_real = discriminator(real)
    loss_real = criterion(D_real, real_labels)

    # Fake Loss
    D_fake = discriminator(fake.detach())
    loss_fake = criterion(D_fake, fake_labels)

    # Total Loss
    loss_D = loss_real + loss_fake

    optimizer_d.zero_grad()
    loss_D.backward()
    optimizer_d.step()

    # Train Discriminator
    output = discriminator(fake)
    g_loss = criterion(output, real_labels) # wants Discriminator to think fake is real

    optimizer_g.zero_grad()
    g_loss.backward()
    optimizer_g.step()
  show_images(real)
  show_images(fake)
  print(f"Epoch [{epoch}/{epochs}], Loss D: {loss_D.item()}, Loss G: {g_loss.item()}")







# =============================================================================
# EXTENSION: Higher-Resolution 64x64 Image Generation
# =============================================================================
# Architectural upgrades over the 28x28 baseline above:
#
#  Generator  – 5-stage progressive upsampling (1x1 → 4 → 8 → 16 → 32 → 64)
#               mixing ConvTranspose2d, bilinear upsample+conv, and PixelShuffle
#               to avoid checkerboard artifacts at each scale.
#  Discriminator – Spectral Normalisation on every Conv2d to bound the
#               Lipschitz constant, preventing the disc from overpowering
#               the generator and reducing mode collapse at higher resolution.
#  ResBlock   – shared residual block used in both networks for gradient flow.
#  weights_init – Kaiming initialisation for faster, more stable convergence.
#  fixed_noise – constant latent vectors so per-epoch samples are comparable.
# =============================================================================

import torch.nn.functional as F


# ---------------------------------------------------------------------------
# Shared Residual Block
# ---------------------------------------------------------------------------

class ResBlock(nn.Module):
    """Residual block; uses SpectralNorm instead of BatchNorm when spectral_norm=True."""
    def __init__(self, channels, spectral_norm=False):
        super().__init__()
        norm = nn.utils.spectral_norm if spectral_norm else (lambda x: x)
        self.block = nn.Sequential(
            norm(nn.Conv2d(channels, channels, 3, 1, 1, bias=False)),
            nn.BatchNorm2d(channels) if not spectral_norm else nn.Identity(),
            nn.LeakyReLU(0.2, inplace=True),
            norm(nn.Conv2d(channels, channels, 3, 1, 1, bias=False)),
            nn.BatchNorm2d(channels) if not spectral_norm else nn.Identity(),
        )
        self.act = nn.LeakyReLU(0.2, inplace=True)

    def forward(self, x):
        return self.act(x + self.block(x))


# ---------------------------------------------------------------------------
# Generator64  –  z_dim x 1x1  →  1 x 64x64
# ---------------------------------------------------------------------------
#
# Stage 1 ConvTranspose  1x1  → 4x4   (512 ch)   learned projection
# Stage 2 ConvTranspose  4x4  → 8x8   (256 ch)   + ResBlock
# Stage 3 Bilinear+Conv  8x8  → 16x16 (128 ch)   + ResBlock  (no checkerboard)
# Stage 4 Bilinear+Conv  16x16→ 32x32  (64 ch)
# Stage 5 PixelShuffle   32x32→ 64x64   (1 ch)   sharpest final upsample

class Generator64(nn.Module):
    def __init__(self, z_dim=100):
        super().__init__()

        self.stage1 = nn.Sequential(
            nn.ConvTranspose2d(z_dim, 512, 4, 1, 0, bias=False),  # → 4x4
            nn.BatchNorm2d(512),
            nn.ReLU(inplace=True),
        )
        self.stage2 = nn.Sequential(
            nn.ConvTranspose2d(512, 256, 4, 2, 1, bias=False),    # → 8x8
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),
            ResBlock(256),
        )
        self.stage3 = nn.Sequential(
            nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False),  # → 16x16
            nn.Conv2d(256, 128, 3, 1, 1, bias=False),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            ResBlock(128),
        )
        self.stage4 = nn.Sequential(
            nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False),  # → 32x32
            nn.Conv2d(128, 64, 3, 1, 1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
        )
        # PixelShuffle: 64ch 32x32 → 4ch 32x32 → 1ch 64x64
        self.stage5 = nn.Sequential(
            nn.Conv2d(64, 4, 3, 1, 1, bias=False),
            nn.PixelShuffle(2),   # (4, 32, 32) → (1, 64, 64)
            nn.Tanh(),
        )

    def forward(self, z):
        x = self.stage1(z)
        x = self.stage2(x)
        x = self.stage3(x)
        x = self.stage4(x)
        return self.stage5(x)


# ---------------------------------------------------------------------------
# Discriminator64  –  1 x 64x64  →  scalar probability
# ---------------------------------------------------------------------------
# All Conv2d layers are wrapped with SpectralNorm for training stability.

class Discriminator64(nn.Module):
    def __init__(self):
        super().__init__()
        SN = nn.utils.spectral_norm

        self.model = nn.Sequential(
            SN(nn.Conv2d(1,   64,  4, 2, 1, bias=False)),  # 64→32
            nn.LeakyReLU(0.2, inplace=True),

            SN(nn.Conv2d(64,  128, 4, 2, 1, bias=False)),  # 32→16
            nn.LeakyReLU(0.2, inplace=True),
            ResBlock(128, spectral_norm=True),

            SN(nn.Conv2d(128, 256, 4, 2, 1, bias=False)),  # 16→8
            nn.LeakyReLU(0.2, inplace=True),
            ResBlock(256, spectral_norm=True),

            SN(nn.Conv2d(256, 512, 4, 2, 1, bias=False)),  # 8→4
            nn.LeakyReLU(0.2, inplace=True),

            SN(nn.Conv2d(512, 1,   4, 1, 0, bias=False)),  # 4→1
            nn.Sigmoid(),
        )

    def forward(self, x):
        return self.model(x).view(-1, 1)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def show_images_64(tensor, title=""):
    """Display a 4x4 grid of 64x64 generated images."""
    imgs = tensor.detach().cpu()[:16]
    imgs = (imgs * 0.5 + 0.5).clamp(0, 1)  # de-normalise → [0, 1]
    fig, axes = plt.subplots(4, 4, figsize=(7, 7))
    fig.suptitle(title, fontsize=11)
    for i, ax in enumerate(axes.flatten()):
        ax.imshow(imgs[i, 0], cmap='gray')
        ax.axis('off')
    plt.tight_layout()
    plt.show()


def weights_init_64(m):
    """Kaiming init for conv layers; constant init for BatchNorm."""
    cls = m.__class__.__name__
    if 'ConvTranspose' in cls:
        nn.init.kaiming_normal_(m.weight, mode='fan_in',  nonlinearity='relu')
    elif 'Conv' in cls:
        nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='leaky_relu')
    elif 'BatchNorm' in cls:
        nn.init.ones_(m.weight)
        nn.init.zeros_(m.bias)


# ---------------------------------------------------------------------------
# Hyperparameters (64x64 run)
# ---------------------------------------------------------------------------

batch_size_64 = 64      # smaller batch for larger tensors
lr_64         = 0.0002  # standard DCGAN lr
z_dim_64      = 100
epochs_64     = 30
image_size_64 = 64

# ---------------------------------------------------------------------------
# Dataset  –  resize MNIST on-the-fly to 64x64
# ---------------------------------------------------------------------------

transform_64 = transforms.Compose([
    transforms.Resize(image_size_64),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,)),
])

dataset_64    = datasets.MNIST(root='./data', train=True, download=True, transform=transform_64)
dataloader_64 = DataLoader(dataset_64, batch_size=batch_size_64, shuffle=True,
                            num_workers=2, pin_memory=True)

# ---------------------------------------------------------------------------
# Model, optimiser, and loss setup
# ---------------------------------------------------------------------------

criterion_64    = nn.BCELoss()
generator_64    = Generator64(z_dim_64).to(device)
discriminator_64 = Discriminator64().to(device)
generator_64.apply(weights_init_64)
discriminator_64.apply(weights_init_64)

optimizer_g_64 = optim.Adam(generator_64.parameters(),     lr=lr_64, betas=(0.5, 0.999))
optimizer_d_64 = optim.Adam(discriminator_64.parameters(), lr=lr_64, betas=(0.5, 0.999))

# Fixed latent vectors – same every epoch so progress is visually comparable
fixed_noise_64 = torch.randn(16, z_dim_64, 1, 1, device=device)

# ---------------------------------------------------------------------------
# Training loop  (64x64)
# ---------------------------------------------------------------------------

for epoch in range(1, epochs_64 + 1):
    for real_64, _ in dataloader_64:
        real_64    = real_64.to(device)
        bs         = real_64.size(0)

        # ── Discriminator step ──────────────────────────────────────────────
        noise_64      = torch.randn(bs, z_dim_64, 1, 1, device=device)
        fake_64       = generator_64(noise_64)

        real_labels_64 = torch.full((bs, 1), 0.9, device=device)  # label smoothing
        fake_labels_64 = torch.zeros(bs, 1, device=device)

        loss_real_64 = criterion_64(discriminator_64(real_64),          real_labels_64)
        loss_fake_64 = criterion_64(discriminator_64(fake_64.detach()), fake_labels_64)
        loss_D_64    = loss_real_64 + loss_fake_64

        optimizer_d_64.zero_grad()
        loss_D_64.backward()
        optimizer_d_64.step()

        # ── Generator step ──────────────────────────────────────────────────
        gen_labels_64 = torch.ones(bs, 1, device=device)
        g_loss_64     = criterion_64(discriminator_64(fake_64), gen_labels_64)

        optimizer_g_64.zero_grad()
        g_loss_64.backward()
        optimizer_g_64.step()

    # Visualise with fixed noise for consistent epoch-by-epoch comparison
    with torch.no_grad():
        sample_64 = generator_64(fixed_noise_64)
    show_images_64(sample_64, title=f"64x64 – Epoch {epoch}/{epochs_64}")

    print(f"[64x64] Epoch [{epoch:3d}/{epochs_64}]  "
          f"Loss D: {loss_D_64.item():.4f}  Loss G: {g_loss_64.item():.4f}")
