"""
Prometheus metrics module for real-time observability.

Tracks the four golden signals:
- Latency: request duration, LLM call duration, pipeline latency
- Traffic: request count, document uploads, chat sessions
- Errors: HTTP errors, LLM errors, processing errors
- Saturation: active requests, queue depth, vector store queries
"""

from prometheus_client import Counter, Histogram, Gauge, REGISTRY
from typing import Optional
import time
import logging

logger = logging.getLogger(__name__)

# ============================================================================
# NOTE ON HTTP-LEVEL METRICS
# ============================================================================
# Request count, latency, and in-progress requests are already published by
# `prometheus_fastapi_instrumentator` in main.py (http_requests_total,
# http_request_duration_seconds, http_requests_inprogress). We deliberately
# do NOT redefine those metric names here — doing so on the same default
# registry raises `ValueError: Duplicated timeseries in CollectorRegistry`
# at startup. Everything below registers on the same default registry
# Instrumentator uses, so it all shows up together on one /metrics route.
# ============================================================================


# ============================================================================
# 2. CHAT API METRICS
# ============================================================================

CHAT_REQUESTS_TOTAL = Counter(
    "chat_requests_total",
    "Total chat requests processed",
    ["workflow_type", "status"],  # workflow_type: intent_detection, knowledge_rag, agentic_rag
)

CHAT_PROCESSING_DURATION_SECONDS = Histogram(
    "chat_processing_duration_seconds",
    "Time to process chat request (end-to-end)",
    ["workflow_type"],
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0),
)

CHAT_TOKENS_GENERATED = Counter(
    "chat_tokens_generated_total",
    "Total tokens generated by LLM",
    ["model", "workflow_type"],
)

CHAT_TOKENS_CONSUMED = Counter(
    "chat_tokens_consumed_total",
    "Total tokens consumed from LLM",
    ["model", "workflow_type"],
)

CHAT_ERRORS = Counter(
    "chat_errors_total",
    "Total chat processing errors",
    ["workflow_type", "error_type"],
)


# ============================================================================
# 3. LLM / AGENT PERFORMANCE METRICS
# ============================================================================

LLM_CALL_DURATION_SECONDS = Histogram(
    "llm_call_duration_seconds",
    "LLM API call latency",
    ["model", "operation"],  # operation: complete, embed, etc.
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0),
)

LLM_CALL_ERRORS = Counter(
    "llm_call_errors_total",
    "LLM API errors",
    ["model", "error_code"],
)

AGENT_INVOCATIONS = Counter(
    "agent_invocations_total",
    "Agent pipeline invocations",
    ["agent_type", "status"],  # agent_type: intent_detector, knowledge_rag, agentic_rag
)

AGENT_STEP_DURATION_SECONDS = Histogram(
    "agent_step_duration_seconds",
    "Duration of individual agent steps",
    ["agent_type", "step_name"],
    buckets=(0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0),
)


# ============================================================================
# 4. RETRIEVAL & VECTOR STORE METRICS
# ============================================================================

VECTOR_STORE_QUERY_DURATION_SECONDS = Histogram(
    "vector_store_query_duration_seconds",
    "Vector store similarity search latency",
    ["store_type", "operation"],  # store_type: pinecone, faiss; operation: query, index
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5),
)

VECTOR_STORE_QUERIES = Counter(
    "vector_store_queries_total",
    "Total vector store queries",
    ["store_type", "operation"],
)

DOCUMENTS_RETRIEVED = Histogram(
    "documents_retrieved",
    "Number of documents retrieved per query",
    ["store_type"],
    buckets=(1, 5, 10, 20, 50),
)

RETRIEVAL_RANK_BM25_DURATION_SECONDS = Histogram(
    "retrieval_rank_bm25_duration_seconds",
    "BM25 ranking duration",
    buckets=(0.001, 0.01, 0.05, 0.1, 0.5),
)


# ============================================================================
# 5. DOCUMENT UPLOAD & PROCESSING METRICS
# ============================================================================

DOCUMENTS_UPLOADED_TOTAL = Counter(
    "documents_uploaded_total",
    "Total documents uploaded",
    ["file_type"],  # file_type: pdf, docx, txt, etc.
)

DOCUMENT_PROCESSING_DURATION_SECONDS = Histogram(
    "document_processing_duration_seconds",
    "Time to process uploaded document",
    ["file_type", "stage"],  # stage: parse, chunk, embed, store
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0),
)

DOCUMENTS_CHUNKED_TOTAL = Counter(
    "documents_chunked_total",
    "Total document chunks created",
)

EMBEDDINGS_GENERATED = Counter(
    "embeddings_generated_total",
    "Total embeddings generated",
)

UPLOAD_ERRORS = Counter(
    "upload_errors_total",
    "Document upload and processing errors",
    ["file_type", "error_type"],
)


# ============================================================================
# 6. SESSION & STATE MANAGEMENT METRICS
# ============================================================================

ACTIVE_SESSIONS = Gauge(
    "active_sessions",
    "Number of active user sessions",
)

SESSION_DURATION_SECONDS = Histogram(
    "session_duration_seconds",
    "Session duration",
    buckets=(60, 300, 600, 1800, 3600, 7200),
)

CHAT_HISTORY_SIZE = Histogram(
    "chat_history_size",
    "Number of messages in chat history",
    buckets=(1, 5, 10, 20, 50),
)


# ============================================================================
# 7. DATABASE & PERSISTENCE METRICS
# ============================================================================

DB_QUERY_DURATION_SECONDS = Histogram(
    "db_query_duration_seconds",
    "Database query latency",
    ["query_type", "operation"],  # query_type: postgres, redis; operation: select, insert, etc.
    buckets=(0.001, 0.01, 0.05, 0.1, 0.5, 1.0),
)

DB_ERRORS = Counter(
    "db_errors_total",
    "Database operation errors",
    ["query_type", "error_type"],
)


# ============================================================================
# 8. SYSTEM HEALTH & SATURATION METRICS
# ============================================================================

SYSTEM_HEALTH_STATUS = Gauge(
    "system_health_status",
    "System health (1=healthy, 0=degraded, -1=down)",
    ["component"],  # component: api, vector_store, db, llm, etc.
)

CACHE_HIT_RATIO = Gauge(
    "cache_hit_ratio",
    "Cache hit ratio (0-1)",
    ["cache_type"],
)

QUEUE_DEPTH = Gauge(
    "queue_depth",
    "Current queue depth for async operations",
    ["queue_name"],
)


# ============================================================================
# Context Managers for Timing
# ============================================================================

class TimerContext:
    """Context manager for recording operation duration."""

    def __init__(self, histogram: Histogram, labels: Optional[dict] = None):
        self.histogram = histogram
        self.labels = labels or {}
        self.start_time = None

    def __enter__(self):
        self.start_time = time.perf_counter()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        elapsed = time.perf_counter() - self.start_time
        self.histogram.labels(**self.labels).observe(elapsed)


class CounterContext:
    """Context manager for incrementing/decrementing active request counters."""

    def __init__(self, inc_counter: Gauge, dec_counter: Optional[Gauge] = None, labels: Optional[dict] = None):
        self.inc_counter = inc_counter
        self.dec_counter = dec_counter
        self.labels = labels or {}

    def __enter__(self):
        self.inc_counter.labels(**self.labels).inc()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.dec_counter:
            self.dec_counter.labels(**self.labels).dec()


# ============================================================================
# Helper Functions
# ============================================================================

# ============================================================================
# Helper Functions
# ============================================================================
# NOTE: HTTP-level recording (request count/duration) is handled automatically
# by prometheus_fastapi_instrumentator in main.py — no helper needed here.

def record_chat_request(workflow_type: str, status: str, duration: float, tokens_used: int = 0, tokens_generated: int = 0, model: str = "gpt-4"):
    """Record a chat request with tokens."""
    CHAT_REQUESTS_TOTAL.labels(
        workflow_type=workflow_type,
        status=status,
    ).inc()

    CHAT_PROCESSING_DURATION_SECONDS.labels(
        workflow_type=workflow_type,
    ).observe(duration)

    if tokens_used > 0:
        CHAT_TOKENS_CONSUMED.labels(
            model=model,
            workflow_type=workflow_type,
        ).inc(tokens_used)

    if tokens_generated > 0:
        CHAT_TOKENS_GENERATED.labels(
            model=model,
            workflow_type=workflow_type,
        ).inc(tokens_generated)


def record_llm_call(model: str, duration: float, operation: str = "complete", error: Optional[str] = None):
    """Record an LLM API call."""
    if error:
        LLM_CALL_ERRORS.labels(model=model, error_code=error).inc()
    else:
        LLM_CALL_DURATION_SECONDS.labels(model=model, operation=operation).observe(duration)


def record_document_upload(file_type: str, total_duration: float, num_chunks: int):
    """Record document upload and processing."""
    DOCUMENTS_UPLOADED_TOTAL.labels(file_type=file_type).inc()
    DOCUMENT_PROCESSING_DURATION_SECONDS.labels(file_type=file_type, stage="total").observe(total_duration)
    DOCUMENTS_CHUNKED_TOTAL.inc(num_chunks)


def get_metrics_summary() -> dict:
    """Get a summary of current metrics (for a lightweight /health or debug endpoint)."""
    return {
        "active_sessions": ACTIVE_SESSIONS._value.get(),
        "chat_requests_total": REGISTRY.get_sample_value("chat_requests_total") or 0,
        "documents_uploaded": REGISTRY.get_sample_value("documents_uploaded_total") or 0,
    }